version: '3.9'
services:
  api:
    build:
      context: ../
      dockerfile: ./docker/api.Dockerfile
    restart: always
    networks:
      - network_containers
    volumes:
      - ../:/home/nodejs/app-mysql
    ports:
      - ${NODE_LOCAL_PORT}:4000
    depends_on:
      db:
        condition: service_healthy

  db:
    restart: always
    networks:
      - network_containers
    build:
      context: ./
      dockerfile: db.Dockerfile
      args:
        - MYSQL_DATABASE=${MYSQLDB_DATABASE}
        - MYSQL_USER=${MYSQLDB_USER}
        - MYSQL_PASSWORD=${MYSQLDB_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQLDB_PASSWORD}
    healthcheck:
      test: "exit 0"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - network_containers
    logging:
      driver: "none"

networks:
  network_containers:
    external: false
